{% set name = "symbolfit" %}
{% set version = "0.2.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/symbolfit-{{ version }}.tar.gz
  sha256: 74c095b346699f2ccfb035213a4f9d7c567d722905dcce7133e29d1a05a6cfba

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python {{ python_min }}
    - setuptools
    - pip
  run:
    - python >={{ python_min }}
    - pysr =1.5.2
    - lmfit >=1.2.0,<1.4.0
    - matplotlib-base >=3.8.0,<4.0.0
    - seaborn >=0.13.0,<0.14.0
    - numpy <2.0.0

test:
  imports:
    - symbolfit
  commands:
    - pip check
  requires:
    - pip
    - python {{ python_min }}

about:
  home: https://github.com/hftsoi/symbolfit
  summary: Automatic parametric modeling with symbolic regression
  license: MIT
  license_file: LICENSE
  description: |
    An API to automate parametric modeling with symbolic regression, originally developed for data analysis in the experimental high-energy physics community, but also applicable beyond.
  doc_url: https://symbolfit.readthedocs.io

extra:
  recipe-maintainers:
    - hftsoi
