{% set name = "symbolfit" %}
{% set version = "0.1.5" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/symbolfit-{{ version }}.tar.gz
  sha256: 592af41737afa4cd6d6b0901edb1b6f0cc73fa9466dc09bce434d8429ebd1b12

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.9
    - setuptools
    - pip
  run:
    - python >=3.9
    - pysr >=0.16.0,<0.20.0
    - lmfit >=1.2.0,<1.4.0
    - matplotlib-base >=3.8.0,<4.0.0
    - seaborn >=0.13.0,<0.14.0
    - numpy <2.0.0

test:
  imports:
    - symbolfit
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://github.com/hftsoi/symbolfit
  summary: Automatic parametric modeling with symbolic regression
  license: MIT
  license_file: LICENSE
  description: |
    An API to automate parametric modeling with symbolic regression, originally developed for data analysis in the experimental high-energy physics community, but also applicable beyond.
  doc_url: https://symbolfit.readthedocs.io

extra:
  recipe-maintainers:
    - hftsoi
